workspace = { members = ["default_macro_derive"] }
[package]
name = "default_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
default_macro_derive = { path = "./default_macro_derive" }
