[package]
name = "generate_a_screte_number"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5" # 实际上是"^0.8.5", 至少是 0.8.5, 但小于 0.9.0 版本
